//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolyadichiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class StepCargo
    {
        public int CargoUnitID { get; set; }
        public string FileName { get; set; }
        public string TransportNumber { get; set; }
        public string SmgsNumber { get; set; }
        public string SmgsDate { get; set; }
        public string DeclarationNumber { get; set; }
        public string DeclarationDate { get; set; }
        public string AccountNumber { get; set; }
        public string AccountDate { get; set; }
        public string RegistrationNumber { get; set; }
        public string RegistrationDate { get; set; }
        public string TempDislocationNumber { get; set; }
        public string TempDislocationDate { get; set; }
    }
}
